name: Build

on: [push, pull_request]

env:

  NODE_VERSION: 16.x

jobs:

  build-android:

    name: Build for Android

    runs-on: ubuntu-latest
    steps: 
    
  - name: Checkout
    uses: actions/checkout@v2

  - name: Set up Node.js
    uses: actions/setup-node@v2
    with:
      node-version: ${{ env.NODE_VERSION }}

  - name: Build with Buildozer
    uses: ArtemSBulgakov/buildozer-action@v1
    id: buildozer
    with:
      workdir: .
      buildozer_version: stable

  - name: Upload artifacts
    uses: actions/upload-artifact@v2
    with:
      name: package
      path: ${{ steps.buildozer.outputs.filename }}
